// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sqkqeudnmcygguombmpi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNxa3FldWRubWN5Z2d1b21ibXBpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyOTQ1MTYsImV4cCI6MjA1OTg3MDUxNn0.giIiv-vV1ZArrcTh5y3XH4MYxO-JbClFKPMMfHfloGE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);