
name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        
      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build
        run: npm run build
        
      - name: Copy CNAME
        run: cp CNAME dist/ || echo "No CNAME file found, skipping..."
        
      - name: Add .nojekyll file
        run: touch dist/.nojekyll
        
      - name: Copy 404.html
        run: |
          if [ -f public/404.html ]; then
            cp public/404.html dist/404.html
            echo "Copied 404.html from public directory"
          else
            echo "<!DOCTYPE html><html><head><meta charset=\"utf-8\"><title>Redirecting...</title><script>sessionStorage.redirect=location.href;location.href='/';</script></head><body></body></html>" > dist/404.html
            echo "Created default 404.html"
          fi
        
      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: dist
          branch: gh-pages

